---
- hosts: postgresql
  become: yes
  roles:
  - role: postgresql
    vars:
    postgresql_version: 15
    postgresql_parameters:
      shared_buffers: "128MB"
      work_mem: "4MB"
      max_connections: 100
      maintenance_work_mem: "1GB"
      wal_buffers: "4MB"
      effective_io_concurrency: 200
      max_worker_processes: 16
      max_parallel_workers_per_gather: 4
      max_parallel_workers: 8
      checkpoint_completion_target: 0.9
      random_page_cost: 1.1
      effective_cache_size: "4GB"
      log_timezone: "Europe/Moscow"
      TimeZone: "Europe/Moscow"
      autovacuum: "on"
      autovacuum_vacuum_cost_delay: "10ms"
      autovacuum_vacuum_cost_limit: 2000
      port: 5433